<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit72d49cd15db23caa0e46ff72a2814a04
{
    public static $classMap = array (
        'PDFMerger' => __DIR__ . '/..' . '/vaza18/pdfmerger/PDFMerger.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit72d49cd15db23caa0e46ff72a2814a04::$classMap;

        }, null, ClassLoader::class);
    }
}
