<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'PDFMerger' => $vendorDir . '/vaza18/pdfmerger/PDFMerger.php',
);
