<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita1337f83864d56bdb6f1cc2170e26f22
{
    public static $classMap = array (
        'PDFMerger' => __DIR__ . '/..' . '/vaza18/pdfmerger/PDFMerger.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInita1337f83864d56bdb6f1cc2170e26f22::$classMap;

        }, null, ClassLoader::class);
    }
}
